name: ci

on:
  push:
    branches:
      - master
    paths:
      - 'app-crypt/**'
      - 'dev-python/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: CI
        id: docker
        uses: osirisinferi/certbot-dns-plugins-ci@v0.5
