name: pkgcheck

on:
  push:
    branches:
      - master
      - development
    paths:
      - 'app-crypt/**'
      - 'dev-python/**'
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'app-crypt/**'
      - 'dev-python/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run pkgcheck
      uses: osirisinferi/pkgcheck-action@v1.1
      with:
        args: --keywords=-RedundantVersion,-MissingAccountIdentifier,-OldPackageUpdate,-VisibleVcsPkg
